model:
  name: 'resnet50'
  pretrained: True

data:
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/'

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.
    weight_x: 1.

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4
  
train:
  optim: 'adam'
  lr: 0.000035
  max_epoch: 120
  batch_size: 64
  lr_scheduler: 'warmup'
  stepsize: [30, 55]

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
  visactmap: False
